import React, { useState } from 'react';
import { X, Code, CheckCircle2, Play, Sliders, RefreshCw, Copy, Check } from 'lucide-react';

export default function LiveCodeSandboxModal({ isOpen, onClose, selectedGame, selectedModel, modelConfig }) {
  if (!isOpen) return null;

  const [code, setCode] = useState(`// AUTOMECHANICA Live Canvas Engine
// Generated by ${modelConfig?.modelName || 'Frontier AI'} for ${selectedGame?.title || 'Game Matrix'}

const engineConfig = {
  theme: "${modelConfig?.version || 'Default'}",
  primaryColor: "${modelConfig?.primaryColor || '#10b981'}",
  deltaLoop: "requestAnimationFrame",
  fpsTarget: 60,
  physicsParameters: {
    friction: 0.985,
    speedMultiplier: 1.25,
    collisionDetection: "Euclidean Spatial Hash",
    audioSynth: "Web Audio API Oscillator Node"
  },
  aiPathfinding: "${modelConfig?.special || 'A* Vector Flanking'}"
};

function renderFrame(ctx, delta) {
  // Real-time canvas render loop
  ctx.fillStyle = "#070a11";
  ctx.fillRect(0, 0, 532, 560);
}`);

  const [copied, setCopied] = useState(false);
  const [applied, setApplied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleApply = () => {
    setApplied(true);
    setTimeout(() => {
      setApplied(false);
      onClose();
    }, 1000);
  };

  return (
    <div className="modal-overlay" onClick={onClose} style={{ zIndex: 999999 }}>
      <div 
        className="glass-panel glow-blue" 
        onClick={(e) => e.stopPropagation()}
        style={{ 
          width: '90%', 
          maxWidth: '800px', 
          padding: '24px', 
          display: 'flex', 
          flexDirection: 'column', 
          gap: '18px',
          background: 'rgba(15, 23, 42, 0.95)',
          boxShadow: '0 0 40px rgba(59, 130, 246, 0.4)'
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '12px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <Code size={22} color="var(--cyber-blue)" />
            <div>
              <h3 style={{ fontSize: '1.2rem', color: '#fff', margin: 0 }}>Live In-Browser Code & Physics Sandbox</h3>
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Inspect & modify model execution code in real-time</div>
            </div>
          </div>
          <button onClick={onClose} className="btn btn-outline btn-sm">
            <X size={16} />
          </button>
        </div>

        <div>
          <label style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'block', marginBottom: '6px' }}>
            CANVAS ENGINE CODE SPECIFICATION ({modelConfig?.modelName}):
          </label>
          <textarea 
            rows="12"
            value={code}
            onChange={(e) => setCode(e.target.value)}
            style={{ 
              width: '100%', 
              padding: '14px', 
              borderRadius: '8px', 
              background: '#070a11', 
              border: '1px solid var(--border-subtle)', 
              color: '#34d399', 
              fontFamily: 'var(--font-mono)', 
              fontSize: '0.8rem', 
              outline: 'none',
              lineHeight: '1.5',
              resize: 'vertical'
            }}
          />
        </div>

        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <button className="btn btn-outline btn-sm" onClick={handleCopy}>
            {copied ? <Check size={14} color="#10b981" /> : <Copy size={14} />}
            <span>{copied ? 'Copied Code!' : 'Copy Code'}</span>
          </button>

          <div style={{ display: 'flex', gap: '10px' }}>
            <button className="btn btn-outline btn-sm" onClick={onClose}>Cancel</button>
            <button className="btn btn-emerald btn-sm" onClick={handleApply}>
              {applied ? <CheckCircle2 size={14} /> : <Play size={14} />}
              <span>{applied ? 'Engine Re-compiled!' : 'Apply & Live Re-compile'}</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
